import { ListingActivity, PingActivity } from './activityStorage';

export const mockCategories = [
  { id: 'all', name: 'All Categories' },
  { id: 'groceries', name: 'Groceries' },
  { id: 'fruits', name: 'Fruits' },
  { id: 'food', name: 'Food' },
  { id: 'services', name: 'Services' },
  { id: 'art', name: 'Art' },
  { id: 'rental', name: 'Rental' },
  { id: 'vehicles', name: 'Vehicles' },
  { id: 'others', name: 'Others' },
];

export const mockListings = [
  {
    id: '1',
    title: 'Fresh Organic Tomatoes',
    price: '80',
    category: 'groceries',
    image: 'https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=400',
    username: 'user_1',
    distance: '0.5 km',
    isActive: true,
  },
  {
    id: '2',
    title: 'Handmade Wooden Table',
    price: '2500',
    category: 'home',
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=400',
    username: 'user_2',
    distance: '1.2 km',
    isActive: true,
  },
  {
    id: '3',
    title: 'iPhone 13 Pro',
    price: '65000',
    category: 'electronics',
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=400',
    username: 'user_3',
    distance: '2.1 km',
    isActive: false,
  },
  {
    id: '4',
    title: 'Fresh Mangoes',
    price: '120',
    category: 'fruits',
    image: 'https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=400',
    username: 'user_1',
    distance: '0.8 km',
    isActive: true,
  },
  {
    id: '5',
    title: 'Home Cleaning Service',
    price: '500',
    category: 'services',
    image: 'https://images.pexels.com/photos/4239091/pexels-photo-4239091.jpeg?auto=compress&cs=tinysrgb&w=400',
    username: 'user_2',
    distance: '1.5 km',
    isActive: true,
  },
  {
    id: '6',
    title: 'Designer Kurta',
    price: '1200',
    category: 'fashion',
    image: 'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=400',
    username: 'user_3',
    distance: '3.2 km',
    isActive: true,
  },
  {
    id: 'demo-1',
    username: 'demo_user',
    title: 'Demo Product',
    description: 'This is a demo product for image testing.',
    price: '100',
    images: ['https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=400'],
    created_at: new Date().toISOString(),
    category: 'groceries',
    distance: '1 km',
    isActive: true,
  },
];

export const mockMessages = [
  {
    id: '1',
    type: 'received',
    name: 'Anjali Verma',
    avatar: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=400',
    location: 'Bandra, Mumbai',
    time: '2h ago',
    productName: 'Fresh Organic Tomatoes',
    productImage: 'https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: '80',
    message: 'Hi! I am interested in buying these tomatoes. Are they still available? Can I pick them up today?',
    status: 'pending',
  },
  {
    id: '2',
    type: 'sent',
    name: 'Vikram Gupta',
    avatar: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=400',
    location: 'Andheri, Mumbai',
    time: '4h ago',
    productName: 'Handmade Wooden Table',
    productImage: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: '2500',
    message: 'Hello, I saw your wooden table. Is it still available? I can come and check it out tomorrow.',
    status: 'accepted',
  },
  {
    id: '3',
    type: 'received',
    name: 'Rohit Sharma',
    avatar: 'https://images.pexels.com/photos/1040880/pexels-photo-1040880.jpeg?auto=compress&cs=tinysrgb&w=400',
    location: 'Dadar, Mumbai',
    time: '1d ago',
    productName: 'iPhone 13 Pro',
    productImage: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: '65000',
    message: 'Is this iPhone in good condition? Any scratches or damage? Can you share more photos?',
    status: 'rejected',
  },
  {
    id: '4',
    type: 'sent',
    name: 'Kavita Rao',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400',
    location: 'Powai, Mumbai',
    time: '2d ago',
    productName: 'Fresh Mangoes',
    productImage: 'https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=400',
    price: '120',
    message: 'Hi, I need 2 kg of mangoes. Are they sweet? When is the best time to pick them up?',
    status: 'pending',
  },
];

export const mockActivity: (ListingActivity | PingActivity)[] = [
  {
    id: 'listing_1',
    type: 'listing',
    listingId: 'listing_1',
    title: 'Fresh Apples',
    price: '120',
    image: 'https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=400',
    isActive: true,
    createdAt: new Date(),
  },
  // Sent ping for user_1
  {
    id: 'ping_sent_user1',
    type: 'sent_ping',
    listingId: 'listing_1',
    listingTitle: 'Fresh Apples',
    listingImage: 'https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=400',
    username: 'user_1',
    userName: 'You',
    userAvatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400',
    message: 'Hi, I am interested in your apples!',
    status: 'pending',
    price: '120',
    createdAt: new Date(),
  },
  // Received ping for user_1
  {
    id: 'ping_received_user1',
    type: 'received_ping',
    listingId: 'listing_1',
    listingTitle: 'Fresh Apples',
    listingImage: 'https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=400',
    username: 'user_1',
    userName: 'Alice',
    userAvatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    message: 'Is this still available?',
    status: 'pending',
    price: '120',
    createdAt: new Date(),
  },
  // Other pings for other users
  {
    id: 'ping_3',
    type: 'sent_ping',
    listingId: 'listing_1',
    listingTitle: 'Fresh Apples',
    listingImage: 'https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=400',
    username: 'user_2',
    userName: 'Bob',
    userAvatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    message: 'Can you deliver?',
    status: 'pending',
    price: '120',
    createdAt: new Date(),
  },
  {
    id: 'ping_4',
    type: 'received_ping',
    listingId: 'listing_1',
    listingTitle: 'Fresh Apples',
    listingImage: 'https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=400',
    username: 'user_2',
    userName: 'Charlie',
    userAvatar: 'https://randomuser.me/api/portraits/men/45.jpg',
    message: 'Is pickup possible?',
    status: 'pending',
    price: '120',
    createdAt: new Date(),
  },
  // Sent ping for user_1 (accepted)
  {
    id: 'ping_sent_user1_accepted',
    type: 'sent_ping',
    listingId: 'listing_2',
    listingTitle: 'Handmade Wooden Table',
    listingImage: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=400',
    username: 'user_1',
    userName: 'You',
    userAvatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400',
    message: 'Is the table still available? Can I see it today?',
    status: 'accepted',
    price: '2500',
    createdAt: new Date(),
  },
  // Received ping for user_1 (rejected)
  {
    id: 'ping_received_user1_rejected',
    type: 'received_ping',
    listingId: 'listing_2',
    listingTitle: 'Handmade Wooden Table',
    listingImage: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=400',
    username: 'user_1',
    userName: 'Priya Sharma',
    userAvatar: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=400',
    message: 'Can you deliver the table to my home?',
    status: 'rejected',
    price: '2500',
    createdAt: new Date(),
  },
  // Sent ping for user_1 (pending, different listing)
  {
    id: 'ping_sent_user1_pending2',
    type: 'sent_ping',
    listingId: 'listing_4',
    listingTitle: 'Fresh Mangoes',
    listingImage: 'https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=400',
    username: 'user_1',
    userName: 'You',
    userAvatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400',
    message: 'Are the mangoes sweet? Can I get 2kg?',
    status: 'pending',
    price: '120',
    createdAt: new Date(),
  },
  // Received ping for user_1 (accepted, different listing)
  {
    id: 'ping_received_user1_accepted2',
    type: 'received_ping',
    listingId: 'listing_4',
    listingTitle: 'Fresh Mangoes',
    listingImage: 'https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=400',
    username: 'user_1',
    userName: 'Sunita Devi',
    userAvatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400',
    message: 'Hi, are you still interested in mangoes?',
    status: 'accepted',
    price: '120',
    createdAt: new Date(),
  },
  // Sent ping for another user (user_3)
  {
    id: 'ping_sent_user3',
    type: 'sent_ping',
    listingId: 'listing_5',
    listingTitle: 'Home Cleaning Service',
    listingImage: 'https://images.pexels.com/photos/4239091/pexels-photo-4239091.jpeg?auto=compress&cs=tinysrgb&w=400',
    username: 'user_3',
    userName: 'Amit',
    userAvatar: 'https://randomuser.me/api/portraits/men/33.jpg',
    message: 'Can you come on Sunday?',
    status: 'pending',
    price: '500',
    createdAt: new Date(),
  },
  // Received ping for another user (user_3)
  {
    id: 'ping_received_user3',
    type: 'received_ping',
    listingId: 'listing_5',
    listingTitle: 'Home Cleaning Service',
    listingImage: 'https://images.pexels.com/photos/4239091/pexels-photo-4239091.jpeg?auto=compress&cs=tinysrgb&w=400',
    username: 'user_3',
    userName: 'Ravi Singh',
    userAvatar: 'https://images.pexels.com/photos/1040880/pexels-photo-1040880.jpeg?auto=compress&cs=tinysrgb&w=400',
    message: 'We are available for cleaning on Sunday.',
    status: 'accepted',
    price: '500',
    createdAt: new Date(),
  },
];